language: dart

env:
  global:
    - DARTSDK=./flutter/bin/cache/dart-sdk/bin
    - DARTFMT=$DARTSDK/dartfmt
    - DARTANALYZER=$DARTSDK/dartanalyzer
    - CODECOV=https://codecov.io/bash
    - PACKAGES=packages

jobs:
  include:
    - stage: Formatting
      script:
        - $DARTFMT -n .

    - stage: Static Analysis
      script:
        - $DARTANALYZER .

    - stage: Test
      script:
        - pub run test .
      after_success:
        - bash <(curl -s $CODECOV)