language: dart

env:
  global:
    - DARTSDK=./flutter/bin/cache/dart-sdk/bin
    - DARTFMT=$DARTSDK/dartfmt
    - DARTANALYZER=$DARTSDK/dartanalyzer
    - CODECOV=https://codecov.io/bash

install:
  - git clone $FLUTTER_GITHUB -b stable --depth 1
  - $FLUTTER doctor
  - $FLUTTER pub get

jobs:
  include:
    - stage: Formatting
      script:
        - $DARTFMT -n . --set-exit-if-changed

    - stage: Static Analysis
      script:
        - $DARTANALYZER .

    - stage: Test
      script:
        - pub run test .
      after_success:
        - bash <(curl -s $CODECOV)