name: dart_katas
description: >-
  These are coding exercises meant to sharpen your programming abilities, 
  analogous to martial arts'. 
  All of the katas were done using TDD, meaning they are not only tested by were
  tailored for (driven by) them.
version: 0.6.1
author: Philippe Fanaro <philippefanaro@gmail.com>
repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: '>=2.5.1 <3.0.0'

dev_dependencies:
  test: ^1.14.6

dependencies:
  meta: ^1.1.8
  rxdart: ^0.24.1