name: game_of_life
description: >-
  OOP Kata for the Game of Life.
version: 0.0.1
author: Philippe Fanaro <philippefanaro@gmail.com>
repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.14.6