name: genetic_algorithm
description: >-
  OOP Kata for the genetic algorithm. Based on [this post](https://lethain.com/genetic-algorithms-cool-name-damn-simple/).
version: 0.0.1
author: Philippe Fanaro <philippefanaro@gmail.com>
repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.14.6