@startuml genetic_algorithm
set namespaceSeparator ::

class "genetic_algorithm::src::evolution_simulator.dart::GeneticEvolutionSimulator" {
  -BehaviorSubject<Population> _populationStreamController
  -Population _currentPopulation
  +dynamic populationStream
  +Population currentPopulation
  +void evolve()
}

"genetic_algorithm::src::evolution_simulator.dart::GeneticEvolutionSimulator" o-- "rxdart::src::subjects::behavior_subject.dart::BehaviorSubject<Population>"
"genetic_algorithm::src::evolution_simulator.dart::GeneticEvolutionSimulator" o-- "genetic_algorithm::src::population.dart::Population"

class "genetic_algorithm::src::individual.dart::Individual" {
  {static} +Random randomNumberGenerator
  -List<int> _values
  +List<int> values
  {static} -List _createRandomList()
  +double calculateFitness()
  +bool ==()
  +String toString()
}

"genetic_algorithm::src::individual.dart::Individual" o-- "dart::math::Random"

class "genetic_algorithm::src::params.dart::IndividualParams" {
  {static} +int defaultLength
  {static} +int defaultRandomGeneratorCeiling
  +List<int> values
  +int length
  +int randomGeneratorCeiling
}

class "genetic_algorithm::src::params.dart::PopulationParams" {
  {static} +int defaultPopulationSize
  +List<Individual> individuals
  +IndividualParams individualParams
  +int size
}

"genetic_algorithm::src::params.dart::PopulationParams" o-- "genetic_algorithm::src::params.dart::IndividualParams"

class "genetic_algorithm::src::population.dart::Population" {
  -List<Individual> _individuals
  +List<Individual> individuals
  {static} -List _createRandomIndividualsList()
  +double calculateGrade()
  +bool ==()
  +String toString()
}


@enduml