name: bowling_game
description: >-
  Bowling Game Kata, based on [Uncle Bob's presentation](http://butunclebob.com/ArticleS.UncleBob.TheBowlingGameKata).
version: 0.0.1
author: Philippe Fanaro <philippefanaro@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'